add python3 support (#33)
* py3: fix print statements

* py3: fix pylint error [E1608(old-octal-literal), ] Use of old octal literal

* py3: fix pylint error [E1604(old-raise-syntax), main] Use raise ErrorClass(args) instead of raise ErrorClass, args.

* py3: use python3 compatible exception syntax

* py3: fix pylint error [W1639(filter-builtin-not-iterating), archive] filter built-in referenced when not iterating

* py3: fix comparison NoneType with int

Traceback (most recent call last):
  File "adm/makedist.py", line 112, in <module>
    main()
  File "adm/makedist.py", line 46, in main
    stage()     # Stage the files we want to distribute
  File "adm/makedist.py", line 95, in stage
    fileutil.cpdir(srcDir, os.path.join(stageDir, dirName), exclude)
  File "/home/developer/data/Sync/work/BC/sedona/adm/fileutil.py", line 67, in cpdir
    if excludematch(exclude, file): continue
  File "/home/developer/data/Sync/work/BC/sedona/adm/fileutil.py", line 44, in excludematch
    if length > 0: return 1
TypeError: '>' not supported between instances of 'NoneType' and 'int'

*  py3: fix pylint error [W1655(dict-keys-not-iterating), dump] dict.keys referenced when not iterating

* py3: enable python3 usage by default

* py3k: use python3 in travis CI